services:
  mysql:
    image: mysql:8.0
    container_name: shared-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --innodb-buffer-pool-size=128M
      --max-connections=100
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    name: backend
    external: false
